### PR TITLE
Fix font and add Meta

### LINKED ISSUE #3: Wrong font for Hack Club `h`
I think the font for the original Hack Club `h` is Amaranth, not Phantom Sans. On the `h`, the top should be angled 45 degrees east of north which seems to be the case in Amaranth, but not Phantom Sans.

### PR DESCRIPTION
**Pull request by exu3**
This PR changes the font of the Hack Club `h` to Amaranth (closes #3) and adds the Meta component from `@hackclub/meta`.

### CODE REVIEW

**Comment by exu3** [comment]
not sure who maintains this repo but Sam seems to be everywhere so cc @sampoder for review please, thanks!

**Review by sampoder — APPROVED** [review]
hmm sure I guess but this repo is dead

**Comment by sampoder** [comment]
thanks tho

**Comment by exu3** [comment]
lol it is, thanks for reviewing anyways!

**Pull request merged**
